docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"

registry:
  - changed-files:
      - any-glob-to-any-file:
          - "registry.json"
          - "registry/**"
          - "public/r/**"
          - "packages/registry/**"

cli:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/cli/**"

web:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/web/**"

packages:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/**"

examples:
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
